- hosts: prod-server
  become: true
  tasks:
  - name: update cache
    apt:
      update_cache: yes
  - name: install docker
    apt:
      pkg: docker.io
      state: present
  - name: start docker service
    service:
      name: docker
      state: started
      enabled: true
  - name: deploy to test-server
    command: docker run -itd -p 80:8082 rchristopher9913/medicure-app:3.0
